### ISSUE TITLE
Incorrect name for SF Clipper

### ISSUE THREAD

**Issue by garyhtou** [hackclub/yellow_pages#1]
My card charge with SF Clipper was incorrectly looked up to be "Amazon". See the screenshot below from HCB.

![image](https://github.com/hackclub/yellow_pages/assets/20099646/d344ed9d-752b-4309-8dd3-1449082ea4d5)
https://hcb.hackclub.com/hcb/QmHZMXm

Here's the raw merchant data from Stripe:
```ruby
"merchant_data" => {
              "url" => nil,
             "city" => "877-669-8368",
             "name" => "CLIPPER SYSTEMS MOBILE #1",
            "state" => "CA",
          "country" => "US",
         "category" => "commuter_transport_and_ferries",
       "network_id" => "4445024897746",
      "postal_code" => "94520",
      "terminal_id" => "16395872",
    "category_code" => "4111"
}
```

**Comment by cjdenio** [comment]
@garyhtou is this in production? The page looks different for me
<img width="647" alt="Screenshot 2024-03-13 at 6 30 19 PM" src="https://github.com/hackclub/yellow_pages/assets/34525547/36479632-ea86-4a90-8242-197095febb7f">

**Comment by cjdenio** [comment]
ah, this is a popover thing

**Comment by cjdenio** [comment]
Transferring this issue to hackclub/hcb since this is an HCB issue
