### ISSUE TITLE
Add `logo` to YAML Schema

### ISSUE THREAD

**Issue by garyhtou** [hackclub/yellow_pages#4]
We have a schema defined here: [hackclub/yellow_pages@main/lib/yellow_pages/merchants.schema.json](https://github.com/hackclub/yellow_pages/blob/main/lib/yellow_pages/merchants.schema.json?rgh-link-date=2024-07-15T20%3A43%3A00Z)

But, it is missing the `logo` field.

**Comment by malted** [comment]
We should remove the logo field. The gem should look up a vendored logo by the `name` of the merchant. See https://github.com/hackclub/yellow_pages/issues/10

**Comment by malted** [comment]
https://github.com/hackclub/yellow_pages/pull/15

**Comment by garyhtou** [comment]
Lookups by `name` feel fragile. Names contain special characters/spaces and can change. Maybe we keep the `logo` field, but it's the file's name/relative path.
