### ISSUE TITLE
Alert on invalid logo URL

### ISSUE THREAD

**Issue by garyhtou** [hackclub/yellow_pages#5]
Our data contains a `logo` field. Some of these URLs are hot-linked from the merchant's website and have the risk of going down.

We should spin up a GitHub actions job that will notify us if any of these logo URLs do not respond with a 2XX.

On a unrelated note, all logo should be CDN'ed to help resolve this issue as well as potential CORs problems.

**Comment by garyhtou** [comment]
> On a unrelated note, all logo should be CDN'ed to help resolve this issue as well as potential CORs problems.

Opened an issue for this: https://github.com/hackclub/yellow_pages/issues/6

**Comment by malted** [comment]
We should vendor the logos instead. https://github.com/hackclub/yellow_pages/issues/10

**Comment by garyhtou** [comment]
Yup!
