### ISSUE TITLE
Normalize data on initial load

### ISSUE THREAD

**Issue by garyhtou** [hackclub/yellow_pages#7]
In order to lookup a merchant by `network_id`, we have to do two types of checks (https://github.com/hackclub/yellow_pages/blob/main/lib/yellow_pages/merchant.rb#L9-L12):
1. String comparison
2. Array includes

This is because the YAML schema for `network_id` can be either a string or an array: https://github.com/hackclub/yellow_pages/blob/main/lib/yellow_pages/merchants.schema.json#L6-L7

To make lookups faster, we should normalize this data when initially loading it. Ideally, we have one giant hash with the keys being a single `network_id`. This means we may have duplicate hash values. We're trading space (memory) for performance.

**Comment by malted** [comment]
Let's get rid of `network_id` https://github.com/hackclub/yellow_pages/issues/9

**Comment by malted** [comment]
The schema is consistent now. `network_ids` is the only option

**Comment by garyhtou** [comment]
> To make lookups faster, we should normalize this data when initially loading it. Ideally, we have one giant hash with the keys being a single `network_id`. This means we may have duplicate hash values. We're trading space (memory) for performance.

Can we also do this? I'd like to make lookups O(1) rather than O(n). lmk if you've got any questions here

**Comment by malted** [comment]
Done!
